{% set name = "mbstrdecoder" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3a258e5e00192281eb774c00637f68d2d460854cea0c5c820aa241732aa0b51

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - releasecmd
  run:
    - chardet >=3.0.4,<5
    - python >=3.5

test:
  imports:
    - mbstrdecoder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/mbstrdecoder
  summary: multi-byte character string decoder
  dev_url: https://github.com/thombashi/mbstrdecoder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
